name: Check SSH

on:
  workflow_call:
    secrets:
      SSH_HOST:
        required: true
      SSH_USER:
        required: true
      SSH_KEY:
        required: true
      KNOWN_HOSTS:
        required: true

jobs:
  check-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} -p22 "ls"
